'use strict';

import "@babel/polyfill";
	import 'nodelist-foreach-polyfill';
	import elementClosest from 'element-closest';
	elementClosest(window);
	import 'formdata-polyfill';
	import 'es6-promise';
	import 'fetch-polyfill';
	import countTimer from './modules/countTimer';
	import togglemenu from './modules/togglemenu';
	import togglePopUp from './modules/togglePopUp';
	import getAnchors from './modules/getAnchors';
	import tabs from './modules/tabs';
	import slider from './modules/slider';
	import changeImg from './modules/changeImg';
	import calcValid from './modules/calcValid';
	import calc from './modules/calc';
	import sendForm from './modules/sendForm';

setInterval(countTimer, 1000, '31 october 2019');
togglemenu();
togglePopUp();
getAnchors();
tabs();
slider();
changeImg();
calcValid();
calc(100);
sendForm();